# Generated by Django 5.2 on 2025-04-24 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('booking', 'Booking'), ('si', 'SI'), ('missions', 'Missions'), ('paiement', 'Paiement'), ('facturation', 'Facturation'), ('taux', 'Taux'), ('service_client', 'Service client'), ('documentation', 'Documentation'), ('autre', 'Autre')], max_length=50)),
                ('nom_structure', models.CharField(max_length=255)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_suivi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statut', models.CharField(default='en_attente', max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_structure', models.CharField(max_length=255)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('booking_number', models.CharField(max_length=100)),
                ('service_concerne', models.CharField(max_length=255)),
                ('note', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField(blank=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
