# Generated by Django 5.2 on 2025-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='nom_prenom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='reclamation',
            old_name='nom_prenom',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='avis',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='booking_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
