# Generated by Django 5.2 on 2025-04-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_avis_user_client_avis_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
