# Generated by Django 5.2 on 2025-05-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_categoriereclamation_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('rejected', 'Rejetée'), ('resolved', 'Résolue')], default='en_attente', max_length=50),
        ),
    ]
