# Generated by Django 5.2 on 2025-05-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_reclamation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('inProgress', 'En cours'), ('rejected', 'Rejetée'), ('resolved', 'Résolue')], default='en_attente', max_length=50),
        ),
    ]
