# Generated by Django 5.2 on 2025-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_remove_reclamation_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='client',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='nom_structure',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='nom_structure',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='avis',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
