# Generated by Django 5.2 on 2025-05-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_remove_reclamation_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='service_concerne',
        ),
    ]
