# Generated by Django 5.2 on 2025-05-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_remove_reclamation_service_concerne'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='service_concerne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.service'),
        ),
    ]
